### ISSUE TITLE
eval "$(pyenv virtualenv-init -)" super slow on MacOS Big Sur

### ISSUE THREAD

**Issue by EmilStenstrom** [pyenv/pyenv-virtualenv#365] opened 2020-08-14 22:21 UTC
Hi,

After installing the public beta of Big Sur every command I type in the terminal takes 2-3 seconds before completing. I've troubleshot it to be because of the `eval "$(pyenv virtualenv-init -)"` line in my bash_profile. There's something in Big Sur that makes that command super slow.

Would you mind giving a couple of hints of where I should start looking for a resolution to this? Having `ls` take 2-3 seconds has already started to make me crazy :)

**Comment by ngaloppo** [comment] 2020-09-17 07:05
I have slow performance on Catalina during bash login startup. It got a bit better when I upgraded to Bash 5.x (with homebrew). It still takes 0.42 to run the `eval $(pyenv virtualenv-init -)` in my `.bashrc`.

**Comment by mrlesmithjr** [comment] 2020-10-02 12:31
Just to add that I have also started seeing this with Mojave using ZSH.

**Comment by ipatch** [comment] 2020-11-11 17:38
this has been an ongoing issue, i ran into this problem several months back, and i use fish shell. i can't remember what it was that i did to "resolve" the issue. but i'm sure this isn't the first time this has been reported. i'll check my dotfiles real quick and see what i can gather because i know first hand how annoying this is.

**Comment by furudean** [comment] 2023-04-20 19:03
This is not specific to fish. Possible duplicate of #259

**Comment by native-api** [comment] 2023-04-20 19:05
Duplicate of https://github.com/pyenv/pyenv-virtualenv/issues/259

**Closed by native-api** 2023-04-20 19:05 UTC
