### ISSUE TITLE
pyenv slows down zsh considerably on Ubuntu 16.04

### ISSUE THREAD

**Issue by Honghe** [pyenv/pyenv-virtualenv#265] opened 2018-05-25 14:23 UTC
log:
```
➜  ~ time pwd
/home/honhe
+ [pyenv:22] enable -f /home/honhe/.pyenv/bin/../libexec/pyenv-realpath.dylib realpath         
+ [pyenv:29] '[' -z '' ']'
++ [pyenv:31] type -p greadlink readlink
++ [pyenv:31] head -1
+ [pyenv:31] READLINK=/bin/readlink
+ [pyenv:32] '[' -n /bin/readlink ']'
+ [pyenv:54] '[' -z '' ']'
+ [pyenv:55] PYENV_ROOT=/home/honhe/.pyenv
+ [pyenv:59] export PYENV_ROOT
+ [pyenv:62] '[' -z '' ']'
+ [pyenv:63] '[' -n '' ']'
+ [pyenv:79] '[' -z '' ']'
+ [pyenv:80] PYENV_DIR=/home/honhe
+ [pyenv:83] '[' '!' -d /home/honhe ']'
+ [pyenv:83] '[' '!' -e /home/honhe ']'
++ [pyenv:87] cd /home/honhe
++ [pyenv:87] echo /home/honhe
+ [pyenv:87] PYENV_DIR=/home/honhe
+ [pyenv:88] export PYENV_DIR
+ [pyenv:91] shopt -s nullglob
++ [pyenv:93] abs_dirname /home/honhe/.pyenv/bin/pyenv
++ [pyenv:39] local path=/home/honhe/.pyenv/bin/pyenv
++ [pyenv:43] '[' -n /home/honhe/.pyenv/bin/pyenv ']'
++ [pyenv:44] cd /home/honhe/.pyenv/bin
++ [pyenv:45] local name=pyenv
+++ [pyenv:46] resolve_link pyenv
+++ [pyenv:35] /bin/readlink pyenv
++ [pyenv:46] path=../libexec/pyenv
++ [pyenv:43] '[' -n ../libexec/pyenv ']'
++ [pyenv:44] cd ../libexec
++ [pyenv:45] local name=pyenv
+++ [pyenv:46] resolve_link pyenv
+++ [pyenv:35] /bin/readlink pyenv
+++ [pyenv:46] true
++ [pyenv:46] path=
++ [pyenv:43] '[' -n '' ']'
++ [pyenv:49] pwd
+ [pyenv:93] bin_path=/home/honhe/.pyenv/libexec
+ [pyenv:94] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
+ [pyenv:95] PATH=/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:94] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
+ [pyenv:95] PATH=/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:94] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
+ [pyenv:95] PATH=/home/honhe/.pyenv/plugins/pyenv-update/bin:/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:94] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
+ [pyenv:95] PATH=/home/honhe/.pyenv/plugins/pyenv-virtualenv/bin:/home/honhe/.pyenv/plugins/pyenv-update/bin:/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:94] for plugin_bin in '"${PYENV_ROOT}/plugins/"*/bin'
+ [pyenv:95] PATH=/home/honhe/.pyenv/plugins/python-build/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/bin:/home/honhe/.pyenv/plugins/pyenv-update/bin:/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:97] export PATH=/home/honhe/.pyenv/libexec:/home/honhe/.pyenv/plugins/python-build/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/bin:/home/honhe/.pyenv/plugins/pyenv-update/bin:/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:97] PATH=/home/honhe/.pyenv/libexec:/home/honhe/.pyenv/plugins/python-build/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/bin:/home/honhe/.pyenv/plugins/pyenv-update/bin:/home/honhe/.pyenv/plugins/pyenv-installer/bin:/home/honhe/.pyenv/plugins/pyenv-doctor/bin:/home/honhe/.phpbrew/bin:/home/honhe/.pyenv/plugins/pyenv-virtualenv/shims:/home/honhe/.pyenv/shims:/home/honhe/.pyenv/bin:/home/honhe/app/swift/usr/bin:/home/honhe/.yarn/bin:/home/honhe/a/app/flutter/bin:/home/honhe/.cargo/bin:/home/honhe/bin:/home/honhe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/honhe/go/bin:/home/honhe/.rvm/bin:/home/honhe/Android/Sdk/tools:/home/honhe/Android/Sdk/platform-tools:/usr/local/go/bin:/home/honhe/.rvm/bin:/home/honhe/bin:/home/honhe/app/scala-2.12.4/bin:/home/honhe/app/sbt/bin
+ [pyenv:99] PYENV_HOOK_PATH=:/home/honhe/.pyenv/pyenv.d
+ [pyenv:100] '[' /home/honhe/.pyenv '!=' /home/honhe/.pyenv ']'
+ [pyenv:104] PYENV_HOOK_PATH=:/home/honhe/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks
+ [pyenv:105] for plugin_hook in '"${PYENV_ROOT}/plugins/"*/etc/pyenv.d'
+ [pyenv:106] PYENV_HOOK_PATH=:/home/honhe/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/honhe/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d
+ [pyenv:105] for plugin_hook in '"${PYENV_ROOT}/plugins/"*/etc/pyenv.d'
+ [pyenv:106] PYENV_HOOK_PATH=:/home/honhe/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/honhe/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/honhe/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:108] PYENV_HOOK_PATH=/home/honhe/.pyenv/pyenv.d:/usr/local/etc/pyenv.d:/etc/pyenv.d:/usr/lib/pyenv/hooks:/home/honhe/.pyenv/plugins/pyenv-virtualenv/etc/pyenv.d:/home/honhe/.pyenv/plugins/pyenv-which-ext/etc/pyenv.d
+ [pyenv:109] export PYENV_HOOK_PATH
+ [pyenv:111] shopt -u nullglob
+ [pyenv:114] command=sh-activate
+ [pyenv:115] case "$command" in
++ [pyenv:128] command -v pyenv-sh-activate
+ [pyenv:128] command_path=/home/honhe/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate
+ [pyenv:129] '[' -z /home/honhe/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate ']'
+ [pyenv:137] shift 1
+ [pyenv:138] '[' --quiet = --help ']'
+ [pyenv:145] exec /home/honhe/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-sh-activate --quiet
+ [pyenv-sh-activate:17] '[' -z /home/honhe/.pyenv ']'
+ [pyenv-sh-activate:25] unset FORCE
+ [pyenv-sh-activate:26] unset QUIET
+ [pyenv-sh-activate:28] '[' 1 -gt 0 ']'
+ [pyenv-sh-activate:29] case "$1" in
+ [pyenv-sh-activate:39] QUIET=1
+ [pyenv-sh-activate:52] shift 1
+ [pyenv-sh-activate:28] '[' 0 -gt 0 ']'
+ [pyenv-sh-activate:55] no_shell=
+ [pyenv-sh-activate:56] versions=("$@")
+ [pyenv-sh-activate:57] '[' -z '' ']'
+ [pyenv-sh-activate:58] no_shell=1
+ [pyenv-sh-activate:59] OLDIFS=' 	
'
+ [pyenv-sh-activate:60] IFS=:
+ [pyenv-sh-activate:60] versions=($(pyenv-version-name 2>/dev/null))
++ [pyenv-sh-activate:60] pyenv-version-name
+ [pyenv-sh-activate:61] IFS=' 	
'
+ [pyenv-sh-activate:64] '[' -z 1 ']'
+ [pyenv-sh-activate:70] venv=system
+ [pyenv-sh-activate:72] '[' -n '' ']'
+ [pyenv-sh-activate:85] pyenv-virtualenv-prefix system
+ [pyenv-sh-activate:87] OLDIFS=' 	
'
+ [pyenv-sh-activate:88] IFS=:
+ [pyenv-sh-activate:88] current_versions=($(pyenv-version-name))
++ [pyenv-sh-activate:88] pyenv-version-name
+ [pyenv-version-name:6] '[' -z '' ']'
++ [pyenv-version-name:7] pyenv-version-file
+ [pyenv-version-file:7] target_dir=
+ [pyenv-version-file:22] '[' -n '' ']'
+ [pyenv-version-file:25] find_local_version_file /home/honhe
+ [pyenv-version-file:10] local root=/home/honhe
+ [pyenv-version-file:11] [[ /home/honhe =~ ^//[^/]*$ ]]
+ [pyenv-version-file:12] '[' -f /home/honhe/.python-version ']'
+ [pyenv-version-file:16] '[' -n /home/honhe ']'
+ [pyenv-version-file:17] root=/home
+ [pyenv-version-file:11] [[ /home =~ ^//[^/]*$ ]]
+ [pyenv-version-file:12] '[' -f /home/.python-version ']'
+ [pyenv-version-file:16] '[' -n /home ']'
+ [pyenv-version-file:17] root=
+ [pyenv-version-file:11] [[ '' =~ ^//[^/]*$ ]]
+ [pyenv-version-file:12] '[' -f /.python-version ']'
+ [pyenv-version-file:16] '[' -n '' ']'
+ [pyenv-version-file:16] break
+ [pyenv-version-file:19] return 1
+ [pyenv-version-file:26] '[' /home/honhe '!=' /home/honhe ']'
+ [pyenv-version-file:27] echo /home/honhe/.pyenv/version
+ [pyenv-version-name:7] PYENV_VERSION_FILE=/home/honhe/.pyenv/version
++ [pyenv-version-name:8] pyenv-version-file-read /home/honhe/.pyenv/version
+ [pyenv-version-file-read:6] VERSION_FILE=/home/honhe/.pyenv/version
+ [pyenv-version-file-read:8] '[' -e /home/honhe/.pyenv/version ']'
+ [pyenv-version-file-read:11] IFS=' 	
'
+ [pyenv-version-file-read:12] words=($(cut -b 1-1024 "$VERSION_FILE" | sed 's/^\s*\(\S\+\).*/\1/'))
++ [pyenv-version-file-read:12] cut -b 1-1024 /home/honhe/.pyenv/version
++ [pyenv-version-file-read:12] sed 's/^\s*\(\S\+\).*/\1/'
+ [pyenv-version-file-read:13] versions=("${words[@]}")
+ [pyenv-version-file-read:15] '[' -n '' ']'
+ [pyenv-version-file-read:22] exit 1
++ [pyenv-version-name:8] true
+ [pyenv-version-name:8] PYENV_VERSION=
+ [pyenv-version-name:11] OLDIFS=' 	
'
+ [pyenv-version-name:12] IFS='
'
+ [pyenv-version-name:12] scripts=(`pyenv-hooks version-name`)
++ [pyenv-version-name:12] pyenv-hooks version-name
+ [pyenv-hooks:9] '[' version-name = --complete ']'
+ [pyenv-hooks:18] PYENV_COMMAND=version-name
+ [pyenv-hooks:19] '[' -z version-name ']'
+ [pyenv-hooks:24] enable -f /home/honhe/.pyenv/libexec/pyenv-realpath.dylib realpath
+ [pyenv-hooks:25] '[' -n '' ']'
++ [pyenv-hooks:29] type -p greadlink readlink
++ [pyenv-hooks:29] head -1
+ [pyenv-hooks:29] READLINK=/bin/readlink
+ [pyenv-hooks:30] '[' -z /bin/readlink ']'
+ [pyenv-hooks:55] IFS=:
+ [pyenv-hooks:55] hook_paths=($PYENV_HOOK_PATH)
+ [pyenv-hooks:57] shopt -s nullglob
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:58] for path in '"${hook_paths[@]}"'
+ [pyenv-hooks:63] shopt -u nullglob
+ [pyenv-version-name:13] IFS=' 	
'
+ [pyenv-version-name:18] '[' -z '' ']'
+ [pyenv-version-name:19] echo system
+ [pyenv-version-name:20] exit
+ [pyenv-sh-activate:89] IFS=' 	
'
+ [pyenv-sh-activate:90] new_venv=system/envs/system
+ [pyenv-sh-activate:91] pyenv-virtualenv-prefix system/envs/system
+ [pyenv-sh-activate:95] '[' -z 1 ']'
+ [pyenv-sh-activate:98] echo false
+ [pyenv-sh-activate:99] exit 1
```

**Comment by furudean** [comment] 2023-04-20 19:05
Duplicate of #259

**Comment by native-api** [comment] 2023-04-20 19:11
Duplicate of https://github.com/pyenv/pyenv-virtualenv/issues/259

**Closed by native-api** 2023-04-20 19:11 UTC
