### ISSUE TITLE
Makes the prompt load super slowly

### ISSUE THREAD

**Issue by nodingneu** [pyenv/pyenv-virtualenv#346] opened 2020-03-04 02:10 UTC
Adding the required

    eval "$(pyenv virtualenv-init -)"

to my zshrc makes the prompt load much slower than without. What's the reason for this?

**Comment by furudean** [comment] 2023-04-20 19:03
Duplicate of #259

**Comment by native-api** [comment] 2023-04-20 19:04
Duplicate of https://github.com/pyenv/pyenv-virtualenv/issues/259

**Closed by native-api** 2023-04-20 19:04 UTC
